Feature/twitter into develop
jarviscanada/jarvis_data_eng_akshay pull request #6
Opened 2020-01-08 07:34 UTC by AkshaySapra

2020-01-09 04:06 UTC, jaypatel-jrvs requested changes
Remove the target folder from your github repo.
The code itself is good to be merged.

2020-01-09 12:03 UTC, jaypatel-jrvs approved these changes

2020-01-09 12:06 UTC, jaypatel-jrvs commented
You can try target/ to ignore the folder maven has some recommended gitignore files somewhere on the internet or you can look at repos of larger organizations

2020-01-13 22:55 UTC, andrew-laniak-fuoco approved these changes

2020-01-13 22:55 UTC, andrew-laniak-fuoco commented on core_java/jdbc/src/main/java/ca/jrvs/apps/jdbc/CustomerDAO.java
> +    public List<Customer> findAllSorted(int limit){
This method name is misleading.

2020-01-13 22:55 UTC, andrew-laniak-fuoco commented on core_java/jdbc/src/main/java/ca/jrvs/apps/jdbc/JDBCExecutor.java
> +        DatabaseConnectionManager dcm = new DatabaseConnectionManager("localhost",
Try using environmental variables.  Hardcoding passwords is dangerous.

2020-01-13 23:02 UTC, merged